### PR TITLE
Fix native install on Fedora 36, add minimal CI

### PR DESCRIPTION
**Pull request by AronNovak**

### CODE REVIEW

**Comment by AronNovak** [comment]
^^ @bderenzi Ready for review.

**Comment by AronNovak** [comment]
^^ @bderenzi After approval + merge, it makes sense to enable the project at CircleCI, for open source projects, it's free, and now the project has minimal build test.

**Comment by AronNovak** [comment]
@bderenzi `outlierdetect/test_outlierdetect.py` - is it supposed to work? In case, we might add this to the CI test job, but seemingly it always fails.

**Comment by AronNovak** [comment]
@bderenzi do you have chance to consider this?

**Comment by AronNovak** [comment]
@bderenzi ^^

**Comment by bderenzi** [comment]
Sorry for the huge delay! 

This is amazing, thanks for all of the work! I'm not familiar with CircleCI. At Dimagi we used to use Travis a while back, but that is no longer recommended. We now use Github Actions for our CI on other repos. 

Do you know the differences or relative advantages or disadvantagesb between Github Actions and CircleCI?

**Comment by AronNovak** [comment]
@bderenzi They are more or less drop-in replacements of each other.

**Comment by bderenzi** [comment]
Okay, great! Sounds like an easy switch if there's some reason we need to shift in the future. Thanks again for the PR and work here!

**Comment by bderenzi** [comment]
Oops, looks like the status badge isn't working on the README. Do I need to configure anything on my end?

**Comment by AronNovak** [comment]
@bderenzi Activate the project after sign-up at https://circleci.com/ , it's free for public repos.

**Comment by bderenzi** [comment]
Super -- all up and running now. On my long todo list is to improve the tests and make them more meaningful.

**Pull request merged**
